eureka:
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/
server:
  port: 8088
spring:
  application:
    name: zuul-server
  data:
    mongodb:
      uri: mongodb://192.168.154.128:27017/linktrace
zuul:
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: consumer-ribbon
    consumer-feign:
      path: /feign/**
    server-linktrace:
      path: /linktrace/**
ribbon:
  eager-load:
    clients: true
  ConnectTimeout: 60000
  ReadTimeout: 60000
  SocketTimeout: 60000