
server:
#  port: 8003
  port: 8004
spring:
  application:
    name: server-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: shares
    url: jdbc:mysql://localhost:3306/shares?useSSL=false&characterEncoding=utf8
    password: 123456
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    removeAbandoned: true
    removeAbandonedTimeout: 60
    logAbandoned: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/

mybatis:
  mapper-locations : classpath:mapper/*Mapper.xml
#mybatis.config-location= classpath:SqlMapConfig.xml
  type-aliases-package : com.soft.shares.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count==countSql
  returnPageInf: check